### ISSUE TITLE
Laravel is failing with dockerizer (cli commands)

### ISSUE THREAD

**Issue by capynet** [frontid/dockerizer#112]
Here is the situation:
You start a dockerized laravel, try to run any "bin" and tyou will see an aoutput indicating some ENV variables are not defined. 

We had a similar issue in the past since laravel uses ENV vars too. We suspect they are coliding. 

If this is the case we will need a prefix for all our variables like `DK_FOO_VAR` or some way to isolate ENV vars one each other...

**Comment by sevanagloria** [comment]
This error was due to a wrong path used to launch docker-composer.
Fixed in #113
