### ISSUE TITLE
Back to traefik_default network maybe?

### ISSUE THREAD

**Issue by capynet** [frontid/dockerizer#62]
Right now We are creating and using `traefik_network` network to have an isolated environment, but maybe we could start using the default `traefik_default` network since at this point a custom network seems not be mandatory.

Another approach could be to have more than one network at the traefik's docker-compose.yml file. Please check both possibilities.

**Comment by keopx** [comment]
Check PR #101

**Comment by sevanagloria** [comment]
I think that having another network allows having different tools ( like ddev, phabalicious, custom deployments ... ) that don't mess with each other.
So leaving our traefik_network is our best approach to interact with other solutions.
