### ISSUE TITLE
ssh-agent volume for SSH_AUTH_SOCK variable

### ISSUE THREAD

**Issue by keopx** [frontid/dockerizer#68]
By default system is using `SSH_CREDENTIALS=/run/user/1000/keyring/ssh` but it only works under Ubuntu version.

If you are using other distro like Debian, recommendation is works with ssh-agent.

Additional command to run ssh-agent:
```bash
$ ssh-add -K
$ ssh-agent
```

Patch:

```diff
diff --git a/docker-compose.override.yml b/docker-compose.override.yml
index 4412306..ba1c63c 100644
--- a/docker-compose.override.yml
+++ b/docker-compose.override.yml
@@ -20,7 +20,7 @@ services:
       PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
       SSH_AUTH_SOCK: /ssh-agent
     volumes:
-      - $SSH_CREDENTIALS:/ssh-agent
+      - ${SSH_AUTH_SOCK}:/ssh-agent
 
   apache:
     network_mode: traefik_network
@@ -91,4 +91,4 @@ services:
 #      POSTGRES_DB: db
 #      PGDATA: /var/lib/postgresql/data/pgdata
 #    volumes:
-#      - ./:/var/www/html
\ No newline at end of file
+#      - ./:/var/www/html

```

**Comment by keopx** [comment]
Applying patch we solved sharing ssh key agent between local machine and
docker container

**Comment by capynet** [comment]
But the issue does not explain the problem and the proposed solution. Is just a patch.

Please explain the problem, the solution the patch implements and if your solution is going to deprecate the var `$SSH_CREDENTIALS` include at the patch the entire deprecation, not just the line you are interested.

**Comment by keopx** [comment]
Ah, ok, sorry. I will edit issue later.

**Comment by keopx** [comment]
@capynet updated

**Comment by capynet** [comment]
Finally we made a new approach using docker4drupal templates. its more transversal and fixes this situation for mac and linux.
